python run_model_data_alpha.py arga_ae cora 0
# python run_model_data_alpha.py arga_ae cora 0.01
# python run_model_data_alpha.py arga_ae cora 0.02
# python run_model_data_alpha.py arga_ae cora 0.03
# python run_model_data_alpha.py arga_ae cora 0.04
# python run_model_data_alpha.py arga_ae cora 0.05
# python run_model_data_alpha.py arga_ae cora 0.06
# python run_model_data_alpha.py arga_ae cora 0.07
# python run_model_data_alpha.py arga_ae cora 0.08
# python run_model_data_alpha.py arga_ae cora 0.09
# python run_model_data_alpha.py arga_ae cora 0.1
# python run_model_data_alpha.py arga_ae cora 0.3
# python run_model_data_alpha.py arga_ae cora 0.5
# python run_model_data_alpha.py arga_ae cora 0.7
# python run_model_data_alpha.py arga_ae cora 1
# python run_model_data_alpha.py arga_ae cora 3
# python run_model_data_alpha.py arga_ae cora 5
# python run_model_data_alpha.py arga_ae cora 7
# python run_model_data_alpha.py arga_ae cora 10
# python run_model_data_alpha.py arga_ae cora 100

python run_model_data_alpha.py arga_vae cora 0
# python run_model_data_alpha.py arga_vae cora 0.01
# python run_model_data_alpha.py arga_vae cora 0.02
# python run_model_data_alpha.py arga_vae cora 0.03
# python run_model_data_alpha.py arga_vae cora 0.04
# python run_model_data_alpha.py arga_vae cora 0.05
# python run_model_data_alpha.py arga_vae cora 0.06
# python run_model_data_alpha.py arga_vae cora 0.07
# python run_model_data_alpha.py arga_vae cora 0.08
# python run_model_data_alpha.py arga_vae cora 0.09
# python run_model_data_alpha.py arga_vae cora 0.1
# python run_model_data_alpha.py arga_vae cora 0.3
# python run_model_data_alpha.py arga_vae cora 0.5
# python run_model_data_alpha.py arga_vae cora 0.7
# python run_model_data_alpha.py arga_vae cora 1
# python run_model_data_alpha.py arga_vae cora 3
# python run_model_data_alpha.py arga_vae cora 5
# python run_model_data_alpha.py arga_vae cora 7
# python run_model_data_alpha.py arga_vae cora 10
# python run_model_data_alpha.py arga_vae cora 100